config/routes.rb
Auto::Application.routes.draw do
  resources :customers

  devise_for :users
  root to: 'customers#index'
  scope shallow_prefix: 'customers' do
    resources :customers do
      resources :payments
    end
  end
  post '/find_number_code' => 'customers#find_number_code'
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :payments
  belongs_to :user
  before_save :normalize_data

  def normalize_data
    self.number_code =  self.number_code.upcase.gsub(' ','')
    self.name =  self.name.capitalize
  end


  def free_payment_left
    6-self.payments_count%7
  end

  def next_free?
   self.free_payment_left == 0 && self.payments_count != 0
  end

end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :customer, :counter_cache => true
  belongs_to :user
  validates :amount, presence: true
  validates :customer_id, presence: true
  validates :description, presence: true, length: { in: 6..220 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :customers
  has_many :payments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_customer, only: [:show,:edit,  :update, :destroy]

  def index
    @customers = Customer.order('created_at DESC').includes(:user, :payments)
  end
  def show

  end
  def new
     @customer = current_user.customers.new
  end
  def create
    @customer = Customer.new(customer_params)
    @customer.user_id = current_user.id
    respond_to do |format|
      if @customer.save
        format.html { redirect_to  @customer, notice: 'Заказчик успешно создан!' }
        format.json { render action: 'show', status: :created, location: @customer }
      else
        format.html { render action: 'new' }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Заказчик успешно обновлен!' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end


  def find_number_code
    q = params[:number_code]
    customers = Customer.where('lower(number_code) LIKE ?',"%#{q.downcase}%").limit(10)
    render json: customers
  end
  private
    def set_customer
      @customer = Customer.find(params[:id])
    end
    def customer_params
      params.require(:customer).permit(:name, :number_code)
    end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: [:show, :edit, :update, :destroy]
  before_action :set_customer, only: [:index, :show, :new, :create]
  before_action :any_free?, only: [:index,:show, :new]

  def index
  end

  def show
  end


  def new
    @payment = @customer.payments.new
  end


  def edit
  end

  def create
    @payment = Payment.new(payment_params)
    @payment.user_id = current_user.id
    respond_to do |format|
      if @payment.save
        format.html { redirect_to  @payment.customer, notice: 'Payment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @payment }
      else
        format.html { render action: 'new' }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to @payment, notice: 'Payment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @payment.destroy
    respond_to do |format|
      format.html { redirect_to :back }
      format.json { head :no_content }
    end
  end

  private
    def set_payment
      @payment = Payment.find(params[:id])
    end
    def set_customer
      @customer = Customer.includes(:payments).find(params[:customer_id])
    end
    def payment_params
      params.require(:payment).permit(:customer_id, :user_id, :amount, :description)
    end
    def any_free?
      if @customer.next_free?
        @free = 'ЭТА МОЙКА БЕСПЛАТНАЯ'
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/customers/_form.html.haml
= form_for @customer, html:{class:'form-horizontal'} do |f|

  - if @customer.errors.any?
    #error_explanation
      %h2= "#{pluralize(@customer.errors.count, "error")} prohibited this payment from being saved:"
      %ul
        - @customer.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    %label.col-lg-2.control-label{for: 'number_code'}
      = f.label 'Номер Авто'
    .col-lg-10
      = f.text_field :number_code, placeholder: 'Номер' , class:'form-control'
      %span.help-block
        Только английские буквы. Пример: 'ap1234ka'
  .form-group
    %label.col-lg-2.control-label{for: 'name'}
      = f.label 'Имя Заказчика'
    .col-lg-10
      = f.text_field :name , placeholder: 'Имя' , class:'form-control'
  .form-group
    = f.submit 'Сохранить', class: 'btn btn-success'
    = link_to 'Назад', customers_path, class:'btn btn-warning'

app/views/customers/edit.html.haml
.container
  .row
    .col-lg-6.col-lg-offset-2
      %h1 Редактирование данных Заказчика
      = render 'form'

app/views/customers/index.html.haml
.container
  .row
    .col-md-3.col-md-offset-3
      =link_to 'Новый Заказчик', new_customer_path, class: 'btn btn-success'
    .col-md-9
      %hr
  .row
    .col-md-9
      %table.table.table-striped.table-hover
        %thead
          %tr
            %th Имя
            %th Номер
            %th Пользователь
            %th Кол-во заказов
            %th До бесплатной осталось
            %th Действия
        %tbody
          - @customers.each do |customer|
            %tr
              %td=customer.name
              %td=customer.number_code
              %td=customer.user.name
              %td=customer.payments_count
              -if customer.next_free?
                %td.text-danger
                  БЕСПЛАТНАЯ
              -else
                %td.text-info= customer.free_payment_left
              %td
                = link_to 'Новый Заказ', new_customer_payment_path(customer) ,class:'btn btn-xs btn-success'
                = link_to 'Показать', customer_payments_path(customer) ,class:'btn btn-xs btn-info'
                = link_to 'Редактировать', edit_customer_path(customer) ,class:'btn btn-xs btn-warning'

app/views/customers/new.html.haml
.container
  .row
    .col-lg-6.col-lg-offset-2
      %h1 Новый Заказчик
      = render 'form'

app/views/customers/show.html.haml
.container
  .row
    .col-lg-6.col-lg-offset-2
      %p
        %b Имя:
        = @customer.name
      %p
        %b Пользователь:
        = @customer.user.name
      %p
        %b Кол-во заказов:
        = @customer.payments_count
      %p
        %b До бесплатной осталось:
        = @customer.free_payment_left
      = link_to 'Edit', edit_customer_path(@customer)
      = link_to 'Back', customers_path

app/views/layouts/_header.haml
.header.navbar.navbar-inverse.navbar-fixed-top
  .header-inner
    %a.text-center.navbar-brand{href: root_path,:style => 'line-height:15px;'} Auto.com
    %form.navbar-form.navbar-left{style:'margin-left: 250px;'}
      %input.form-control.col-lg-8.search_query{type: 'text', placeholder:'Поиск по номерам'}
    %ul.nav.navbar-nav.pull-right
      %li
        %a.username{href: "javascript:;"}
          = current_user.name || current_user.email
        %i.icon-angle-down
        %li
          %a#trigger_fullscreen{href: "javascript:;"}
            %i.fa.fa-arrows-alt
            Full Screen
        %li
          = link_to destroy_user_session_path, :method => :delete    do
            %i.icon-key
            Выйти
%ul.response_box.col-lg-3.col-lg-offset-2

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Auto</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application"%>
  <%= csrf_meta_tags %>
</head>
<body>
<% if flash[:notice] %>
    <div class="alert alert-dismissable alert-success" style="top: 0;position: absolute;width: 100%;z-index: 9999999;">
      <button type="button" class="close" data-dismiss="alert">×</button>
      <%= flash[:notice] %>
    </div>
<% end %>
<% if flash[:alert] %>
    <div class="alert alert-dismissable alert-danger" style="top: 0;position: absolute;width: 100%;z-index: 9999999;">
      <button type="button" class="close" data-dismiss="alert">×</button>
      <%= flash[:alert] %>
    </div>

<% end %>
<%= render 'layouts/header'%>

<%= yield %>

</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Auto</title>
  <%= stylesheet_link_tag    "application", media: "all"%>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if flash[:notice] %>
    <div class="alert alert-dismissable alert-success" style="top: 0;position: absolute;width: 100%;">
      <button type="button" class="close" data-dismiss="alert">×</button>
      <%= flash[:notice] %>
    </div>
<% end %>
<% if flash[:alert] %>
    <div class="alert alert-dismissable alert-danger" style="top: 0;position: absolute;width: 100%;">
      <button type="button" class="close" data-dismiss="alert">×</button>
      <%= flash[:alert] %>
    </div>

<% end %>
    <div class='page-container'>
        <%= yield %>
    </div>
</body>
</html>

app/views/payments/_form.html.haml
= form_for [@payment.customer, @payment], html:{class:'form-horizontal'} do |f|

  - if @payment.errors.any?
    #error_explanation
      %h2= "#{pluralize(@payment.errors.count, "error")} prohibited this payment from being saved:"
      %ul
        - @payment.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    = f.hidden_field :customer_id, value: @customer.id
    %label.col-lg-2.control-label{for: 'amount'}
      = f.label 'Сумма'
    .col-lg-10
      -if @customer.next_free?
        = f.number_field :amount, placeholder: 'Внесенная Сумма' , class:'form-control', value: 0, readonly: true
      -else
        = f.number_field :amount, placeholder: 'Внесенная Сумма' , class:'form-control',value: 0
      %span.help-block
        Записывать в формате: "600" = 6грн, "1550" = 15.50 грн
  .form-group
    %label.col-lg-2.control-label{for: 'description'}
      = f.label 'Описание Услуги'
    .col-lg-10
      = f.text_area :description , placeholder: 'Описание Услуги' , class:'form-control'
      %span.help-block
        Минимальная длинна 6, максимальная - 220 символов
  .form-group
    = f.submit 'Сохранить', class: 'btn btn-success'
    = link_to 'Назад', customer_payments_path, class:'btn btn-warning'

app/views/payments/edit.html.haml
%h1 Editing payment

= render 'form'

= link_to 'Show', @payment
\|
= link_to 'Back', customer_payments_path(@payment.customer)

app/views/payments/index.html.haml
-if @free
  .alert.alert-info.free-car-wash
    %button.close{type:'button', 'data-dismiss'=>'alert'}  ×
    =@free
.container
  .row
    .col-lg-9
      %h1
        Список Оплат Клиента
        %span.text-success
          = @customer.name
      %hr
      %h3
        Всего -
        =@customer.payments_count
      %h3
        До бесплатной осталось -

        %span.text-success
          = @customer.free_payment_left
      %hr
      %table.table.table-striped.table-hover
        %thead
          %tr
            %th Имя
            %th Номер
            %th Пользователь
            %th Сумма (грн)
            %th Описание
            %th Действия
        %tbody
          - @customer.payments.each do |payment|
            %tr
              %td= payment.customer.name
              %td= payment.customer.number_code
              %td= payment.user.name
              %td= payment.amount/100.00
              %td= payment.description
              %td= link_to 'Show', customer_payment_path(@customer,payment) ,class:'btn btn-xs btn-success'
              %td= link_to 'Edit', edit_customer_payment_path(@customer,payment) ,class:'btn btn-xs btn-warning'
              %td= link_to 'Destroy',customer_payment_path(@customer, payment ) ,class:'btn btn-xs btn-danger' , :method => :delete, :data => { :confirm => 'Are you sure?' }

      %br

      = link_to 'Новый Заказ', new_customer_payment_path, class: 'btn btn-success'
      = link_to 'Назад', customers_path, class: 'btn btn-info'

app/views/payments/new.html.haml
-if @free
  .alert.alert-info.free-car-wash
    %button.close{type:'button', 'data-dismiss'=>'alert'}  ×
    =@free
.container
  .row
    .col-lg-6.col-lg-offset-2
      %h1 Новый Заказ
      = render 'form'

app/views/payments/show.html.haml
-if @free
  .alert.alert-info.free-car-wash
    %button.close{type:'button', 'data-dismiss'=>'alert'}  ×
    =@free
%p#notice= notice

%p
  %b Customer:
  = @payment.customer_id
%p
  %b User:
  = @payment.user_id
%p
  %b Amount:
  = @payment.amount/100.00
%p
  %b Description:
  = @payment.description

= link_to 'Edit', edit_customer_payment_path(@payment.customer, @payment)
\|
= link_to 'Back', customer_payments_path(@payment.customer)